{
 "title": "Scaling Terraform Enterprise Real-World Workloads",
 "description": "A Grafana dashboard for Terraform Enterprise ",
 "time": { "from": "2022-11-15T09:19:00.000Z", "to": "2022-11-15T09:39:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(tfe_run_count, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Container Stats (TFE Services)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Worker Container Memory Percentage Utilization",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance, workspace_name, run_type, run_id)(tfe_container_memory_used_bytes{instance=\"$node\",run_type=~\"plan|apply\"} / tfe_container_memory_limit_bytes{instance=\"$node\",run_type=~\"plan|apply\"} * 100)",
     "legendFormat": "{{ workspace_name }} ({{ run_type}} - {{run_id}})"
    }
   ]
  },
  {
   "title": "Run State Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 28, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(workspace_name, status) (tfe_run_current_count{status=~\"plan_queued|planning|apply_queued|applying|pending\"})",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Build Worker Peak Memory Distribution",
   "type": "histogram",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by(run_id) (tfe_container_memory_used_bytes{instance=\"$node\", run_type=~\"plan|apply\"}) / 1024 / 1024",
     "legendFormat": "{{ workspace_name }} ({{ run_type}} - {{run_id}})"
    }
   ]
  }
 ]
}